# Generated by Django 4.2.7 on 2023-12-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=220)),
                ("url", models.URLField()),
                ("img_url", models.URLField()),
                ("current_price", models.FloatField(blank=True)),
                ("old_price", models.FloatField(default=0)),
                ("price_difference", models.FloatField(default=0)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
